### ISSUE TITLE
Redirect urls after login

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#101]
Currently when a redirect param is in the url and a user logs in, it ignores the param and redirects home. It should redirect to that url.

**Comment by noahsark769** [comment]
I can get this one. What's an example of a url that should redirect after login, but doesn't?

**Comment by noahsark769** [comment]
Oh wait you assigned yourself already haha. Lemme know if you need help!

**Comment by vivekraghuram** [comment]
@noahsark769 if you have time feel free to take this one. I figured I'd get to it eventually. An example is if you try to go to something like /donor or /administrator without logging in, it'll redirect you to log in. The URL for the login page will have a param for the redirect url. We should use that redirect after the log in is successful.

**Comment by noahsark769** [comment]
Alright sweet. That should be a relatively easy fix I think.

**Comment by noahsark769** [comment]
Fixed by #102
