### ISSUE TITLE
DASHBOARD MVPs

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#107]
- [ ] Donor (#65)
- [x] Ambassador (#106)
- [ ] Administrator (#66)

**Comment by sameerav** [comment]
![dashboard_menu](https://cloud.githubusercontent.com/assets/7706852/6594933/a4693a44-c7a2-11e4-98d8-f123edf55155.png)
![dashboard]
(https://cloud.githubusercontent.com/assets/7706852/6594941/adea25d8-c7a2-11e4-8d49-9d7895e5924d.png)

dashboard mockup iterations! thoughts @noahsark769 @andylouisqin?

**Comment by noahsark769** [comment]
Wow I LOVE the sidebar, I think it should just always be visible on the administrator and ambassador dashboards. On the donor dash we'll have to tweak it a bit obviously, since there won't be the option to select multiple roles.

1. I think you should add in the top bar with the actual colors, it will change the color distribution of the page a bit so I think it's good to add in now
2. The dashboard pages for projects themselves seem very scattered - what if we had another spedometer type thing (maybe with four stats, but only on the left side? idk) which would initially have some stats and then transition into having repayment stats with the project is complete?
3. IRR is pretty boring and we also need to educate users on it, so maybe it should be in its own paragraph
4. Tags definitely don't need to take up as much space as they do, because especially at first they won't be as important, I think. Which leaves room for:
5. Cover photo: we should definitely have it somewhere!
6. Any idea of how this should work on mobile? lol

**Comment by sameerav** [comment]
1. I was thinking the pills stay gray until hovered over and then the text and border turn their respective colors - do you think the border and text should be colored by default and get filled in when hovered over?
2. Yeah it's pretty disorganized :( I'll try putting in the speedometer thing/coming up with other stuff
3. lol what is IRR even
4. I'll try to fit them under the header or someplace subtle!
5. yes yes yes!
6. LOL I'll try to mock that up later today

**Comment by sameerav** [comment]
![dashboard_description](https://cloud.githubusercontent.com/assets/7706852/6608266/b4c8fdd8-c802-11e4-9610-939a5f9f5dd9.png)

@noahsark769 how about this type of layout instead? If you like it, I'll mock up the rest of the views :)

**Comment by noahsark769** [comment]
Holy shit I think that looks incredible. Can we see it with the revolv bar at the top and the other avenues picture? Also how do you feel about the top buttons being square, since we basically have square buttons everywhere else? @andylouisqin what do you think?

**Comment by andylouisqin** [comment]
Totally agree with @noahsark769  that the sidebar is sexy as hell. I like this! Reminds me of Slack? 

Suggestions:
1. Would hope to switch from pull buttons to the rounded rectangles we've got for consistency.
2. The body of text is pretty wide and would be better at a smaller set width for readability.
3. I'm really considering omitting my nav bar on these dashboards, they definitely don't need to be there all the time am I right?
4. I believe these dashboards should also have a progress bar for funding right? Doesn't have to be fancy, just probably before the body text.
5. Also the sandwich bar menu would probably be best served as a gray, with thinner lines.

**Comment by noahsark769** [comment]
^this

1. Im all about those non-pill buttons. I actually like pills for the category labels though
2. I agree, the text is hella wide. We should try putting int he actual Other Avenues text: I have a feeling some of the paragraphs would be only one line
3. The problem with that is that there's no way to get back to the homepage then...plus you lose the nav controls to signin/out and links to info, etc...I think it would be good to have there. My concern though is that the design will probably look too dark overall: this is fine for the ambassador and administrator dashboards I think, but we could maybe look into having a white sidebar for something for the donor dash?
4. Yeah I think that would go in the "funding" tab. I LOVE the tabs btw they're great
5. I agree, do we even need the sandwich bar menu though? I feel like we do on mobile, but probably not on desktop.

**Comment by noahsark769** [comment]
Other than that I think you should definitely mock up the other tabs, this looks great @sameerav :D

**Comment by sameerav** [comment]
will do! I'll try something with an overall lighter menu on the side so it'll go better with the header

where can I find the other avenue's text?

**Comment by sameerav** [comment]
![dashboard_description_v1](https://cloud.githubusercontent.com/assets/7706852/6657437/791cc4d6-cb09-11e4-8344-7f37aab59204.png)
![dashboard_funding_v1](https://cloud.githubusercontent.com/assets/7706852/6657438/791dbfd0-cb09-11e4-9903-e95e1e9ae25c.png)
![dashboard_repayments_v1](https://cloud.githubusercontent.com/assets/7706852/6657439/791ea5d0-cb09-11e4-8e8b-5bb607d1fc09.png)
![dashboard_updates_v1](https://cloud.githubusercontent.com/assets/7706852/6657436/791c0398-cb09-11e4-99d1-78ba1c6d5072.png)

**Comment by noahsark769** [comment]
lol very nice! Still not sure about the description text, can we pretty please see that page with the actual text from other avenues (and the actual picture)

**Comment by sameerav** [comment]
oh oops totally forgot about that! will do in a bit

**Comment by sameerav** [comment]
![dashboard_description_v1](https://cloud.githubusercontent.com/assets/7706852/6680032/fd8daeaa-cc0e-11e4-9898-4cfeb9cc7bd2.png)
