### ISSUE TITLE
Total statistics display for all donated projects

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#109]
This should be shown when no project is selected on the donor dash. Similar in style to #108 but for ALL projects that a donor has donated to, probably with some kind of thing telling them "You've donated to <num_projects> projects: here's how you've helped" or something like that.

**Comment by sameerav** [comment]
@noahsark769 should i split this issue up into the  7 different sections?

**Comment by noahsark769** [comment]
Sure, if you like. Make sure to assign then the correct priority labels
though
