### ISSUE TITLE
Completed projects in dashboards should show repayment progress

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#119]
Title says it all

**Comment by erictshen** [comment]
Sorry for being behind on this, been busy moving in. I'll make sure to get it in by next weekend.

**Comment by noahsark769** [comment]
Sounds fine, take time to move in!

**Comment by erictshen** [comment]
Also, do you want it to look like this for completed projects as well? (With something else instead of Days Left on the right?)

![791dbfd0-cb09-11e4-9903-e95e1e9ae25c](https://cloud.githubusercontent.com/assets/2114482/7929356/c4c95bc0-08b1-11e5-8878-382e409211cd.png)

**Comment by noahsark769** [comment]
Well, what statistics would you put there? The only ones I can think of are funding goal and repayment progress/amount repaid, so I think we can just have those (maybe we can copy in the statistics from that mockup later, but right now the repayment stats should go by themselves in the "repayments" tab, which should be active by default if the project is complete).

As for aesthetic design though, I think the style of that mockup is a great thing to shoot for!

**Comment by erictshen** [comment]
Cool! I will make sure to get something in by the weekend.

**Comment by noahsark769** [comment]
Sounds great!
