### ISSUE TITLE
Spring 2015 Meeting 1

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#121]
Things to go over:

1. Welcome
2. How the RE-volv app works
3. Workflow
4. High level overview of features that need to be implemented to ship (including schedule for test campaign)
5. Issue triage for the next week: bug fixes and setting infrastructure for large issues, working toward dashboard completion, styles
6. Slack?
7. Move meeting to 1hr meeting/3hr worksession?
8. Scheduling meeting with RE-volv
9. BONDING WITH BLUEOPS

**Comment by aykamko** [comment]
Envision mockups
