### ISSUE TITLE
Sexy animated svg infographic?

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#131]
Andreas is sending me an svg version of the infographic on the homepage. I think it would be really cool if we could take this and make it animated so that the user could get a more interactive feel for how the revolving fundraising works.

**Comment by noahsark769** [comment]
Follow andy's mockup! @andylouisqin++

**Comment by andylouisqin** [comment]
For reference:
![frontpage_mockup 001](https://cloud.githubusercontent.com/assets/3770344/6224188/e5993db6-b62c-11e4-8743-22b5cad2370a.png)
![frontpage_mockup 002](https://cloud.githubusercontent.com/assets/3770344/6224187/e598aa86-b62c-11e4-9679-3348f33d3bf6.png)
![frontpage_mockup 003](https://cloud.githubusercontent.com/assets/3770344/6224186/e5985c70-b62c-11e4-8293-2b292d43b9e6.png)
![frontpage_mockup 004](https://cloud.githubusercontent.com/assets/3770344/6224190/e5a9a624-b62c-11e4-97de-55db7bc6b179.png)
![frontpage_mockup 005](https://cloud.githubusercontent.com/assets/3770344/6224189/e5a7c336-b62c-11e4-9aa8-6deebf60106c.png)

**Comment by noahsark769** [comment]
Fixed by #202
