### ISSUE TITLE
Need new ideas for homepage

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#137]
Everyone comment here with like one idea!

**Comment by erictshen** [comment]
Make the logo more prominent somehow? And make the text in the navbar and footer stand out more?

**Comment by noahsark769** [comment]
That's what I was thinking...what if we did just like a HUGE revolv logo over a full bleed image with the "people funded renewable energy" there instead of in the header?

**Comment by erictshen** [comment]
Sounds good, but would like to see a mock of that.

**Comment by noahsark769** [comment]
I'll try and get one up soon, I'm working on the login page now

**Comment by andylouisqin** [comment]
I have an idea for a revolving animation to explain to users how revolv works. Will show you all a mock this Friday

**Comment by sameerav** [comment]
I have an idea too, i'll have it mocked up by friday

I'm excited to see all the mocks!!!

**Comment by noahsark769** [comment]
Why u close issue? I want to see all of these mocks

**Comment by sameerav** [comment]
oh oops i closed it by accident instead of commenting
sorry noah :(

**Comment by noahsark769** [comment]
Das okay :)

**Comment by noahsark769** [comment]
What about either of these? Not super perfect, but I like the kind of style of the full bleed image. I think I like the one where only the "RE-VOLV" of the logo is white better, not sure though haha.

![revolv-homepage-mockup-whitelogo](https://cloud.githubusercontent.com/assets/1168853/6140316/06689ad2-b14b-11e4-880b-3fff3d484558.png)
![revolv-homepage-mockup](https://cloud.githubusercontent.com/assets/1168853/6140315/0667e2c2-b14b-11e4-9a1c-236a0e780ea8.png)

**Comment by sameerav** [comment]
I like them!

I'm worried about whether it would be engaging for a potential donor, though. The revolv model is a little bit complicated and not intuitive at first, so it might be more effective to communicate it visually somewhere, but I'm not sure where the best place for that would be

**Comment by noahsark769** [comment]
Yeah I was thinking of that too. I think the best place to educate the user
would be in the info graphic, but that's large and there's no room for it
at the top. I was thinking maybe there could be a link in the description
that auto scrolls to the info graphic?

**Comment by noahsark769** [comment]
Good work guys, #131 will actually implement this
