### ISSUE TITLE
Project names that are too long display over boundaries

### ISSUE THREAD

**Issue by erictshen** [calblueprint/revolv#145]
Side bar project name stretches too far
![screen shot 2015-02-09 at 6 43 18 pm](https://cloud.githubusercontent.com/assets/2114482/6162256/9b362b18-b234-11e4-9e88-6d2cfa01ecab.png)

On home page, pages that are too far stretch too far
![screen shot 2015-02-09 at 6 56 47 pm](https://cloud.githubusercontent.com/assets/2114482/6162257/9cd42498-b234-11e4-88df-ea1f3238396a.png)

**Comment by noahsark769** [comment]
I bet it would be fine to just cut it off and do an overflow, since almost all titles will be separated by spaces and thus able to wrap

**Comment by noahsark769** [comment]
Titles will wrap on the new dashboard
