### ISSUE TITLE
Use an actual RE-volv picture for homepage cover

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#188]
Maybe this one from Kehilla? I know we want children, not sure if they have a good quality solar pic with kids though

![kehilla_slide_final picture only](https://cloud.githubusercontent.com/assets/1168853/6570667/915415b0-c6bb-11e4-9442-c96337a9a6be.jpg)

**Comment by andylouisqin** [comment]
Really want solar picture with kids haha, but I'll use this one for now. It is on the lower quality side however.

**Comment by noahsark769** [comment]
I'll ask Andreas if he has any higher quality ones

**Comment by andylouisqin** [comment]
Not too big a fan of this picture for the background. Would appreciate kids in a solar-powered school!

**Comment by noahsark769** [comment]
I asked Andreas but he hasn't gotten back to me :(
