### ISSUE TITLE
Update the project page mockup to include "donation levels"

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#190]

**Comment by noahsark769** [comment]
We did this at the last meeting right? @sameerav can you post that mockup?

**Comment by sameerav** [comment]
@noahsark769  the mockup is pretty janky so here's a screenshot instead
![screen shot 2015-04-15 at 2 32 20 am](https://cloud.githubusercontent.com/assets/7706852/7156303/4abe8d9e-e31a-11e4-8060-4824c426c21b.png)

also, if we don't want to change the layout, my donation level branch is maybe ready for a pull request
it was a really short change just a few random lines

**Comment by noahsark769** [comment]
#236
