### ISSUE TITLE
Homepage styles broken on Firefox

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#207]
The coin falling and all the cool stuff associated with that is broken on Firefox

**Comment by noahsark769** [comment]
@andylouisqin ^

**Comment by noahsark769** [comment]
Wow, it's pretty broken:

![screen shot 2015-03-28 at 5 08 15 pm](https://cloud.githubusercontent.com/assets/1168853/6883125/479c7956-d56d-11e4-807e-1f7fd039b41a.png)

My bad for not checking that it worked on firefox during QA :(

**Comment by andylouisqin** [comment]
Ahhh! Will get to this ASAP. On the brighter side, I think I've found how to fix on mobile

**Comment by andylouisqin** [comment]
Just discovered some broken-ness on Safari too :( 
![screen shot 2015-03-30 at 6 21 54 pm](https://cloud.githubusercontent.com/assets/3770344/6910584/e1cb928a-d709-11e4-82d0-cfdbfcf23329.png)

**Comment by noahsark769** [comment]
bleh :(

**Comment by andylouisqin** [comment]
@noahsark769 this closed be fixed by #218!

**Comment by noahsark769** [comment]
Oh yup, got to used to issues autoclosing themselves
