### ISSUE TITLE
Create and style a 404 page

### ISSUE THREAD

**Issue by andylouisqin** [calblueprint/revolv#252]
Currently if you go to an invalid URL, you get the standard Django traceback.

**Comment by sameerav** [comment]
![404](https://cloud.githubusercontent.com/assets/7706852/7364786/37598b94-ed3f-11e4-8376-10ee54dbec98.png)
pretty basic but thoughts @andylouisqin ?

**Comment by andylouisqin** [comment]
Honestly don't really have objections. The nav bar will still be at the top right? Would also be interesting to have the "email if you think there's been an error" as an HTML mailto button



—

**Comment by sameerav** [comment]
@andylouisqin yeah the navbar would still be there
yeah thats what i was thinking

**Comment by noahsark769** [comment]
I like this, I think the revolv people are really big though haha

**Comment by sameerav** [comment]
![404](https://cloud.githubusercontent.com/assets/7706852/7381841/e54a812c-edbc-11e4-8fc5-0864fcb3a9f9.png)

@noahsark769 smaller revolv people

**Comment by andylouisqin** [comment]
Nice!



—

**Comment by chenhoward** [comment]
Just here to say I love your gh photo @AndyQin++

**Comment by andylouisqin** [comment]
:D



—

**Comment by noahsark769** [comment]
Fixed by #266
