### ISSUE TITLE
Mockup UI for voting on preferences

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#318]
@sameerav this is all you! Mock up the UI for #310. Note that this will go on the dashboard, in the area that shows when there's no specific project showing (we'll also have a link in the dashboard sidebar ("Your Impact") that links back to this page).

**Comment by sameerav** [comment]
![dashboard-categories](https://cloud.githubusercontent.com/assets/7706852/7907905/f78f4bb4-07f3-11e5-8906-dbfbdd7dfaf2.png)
thoughts @noahsark769 ?

**Comment by noahsark769** [comment]
I like it @sameerav! The buttons might look nice in revolv blue as well. My only concern is that people won't be able to find this page dy default, since the "Your Impact" page (with statistics aggregated over every project) needs be shown by default when there is no project selected also. Do you think we could put them on the same page?

**Comment by sameerav** [comment]
@noahsark769 yeah I agree! Let me mock that up.

**Comment by sameerav** [comment]
![your-impact](https://cloud.githubusercontent.com/assets/7706852/7922115/d706fa48-085e-11e5-9d74-98bc172f0265.png)
@noahsark769 thoughts?

**Comment by noahsark769** [comment]
I like the idea! The revolv blue looks really nice and I like the white background as opposed to gray. I think the drawn style of the icons are too casual though: if we do want icons, I think it would be best to copy the info graphic style (could use the same coin).

Also, I feel like right now it's kind of hard to see your actual impact: maybe make the numbers bigger, or on their own line, like the "27 days left" is in that mockup for #107? Another option would just be to use the exact sane design from #107, but just have everything aggregated (though I think icons are great if we can match then to the info graphic style!).

Also, there should be a place for links to all the projects you've donated to!

**Comment by sameerav** [comment]
![your-impact-revolv-blue](https://cloud.githubusercontent.com/assets/7706852/7955454/51b4d0e2-098d-11e5-8bf5-f99e4a8bffbf.png)

updated icons and projects

**Comment by noahsark769** [comment]
@sameerav I like the latest one! What do you think about making the units big and green/yellow/etc too, so that the people see "105 Trees" instead of just "105"? That might be useful. Other than that I think we can get started on building this!

**Comment by sameerav** [comment]
![your-impact-revolv-blue](https://cloud.githubusercontent.com/assets/7706852/7972537/2c9f7b8e-0a02-11e5-9b19-a7d4e1770f77.png)

**Comment by noahsark769** [comment]
I like it! I'll send it to Andreas to see if he has any feedback, but I think it's good to go for now. To implement this, I think it might make sense to do two separate pull requests, one for the "Your Impact" section (#309) and one for the preference vote section (in #310). I'm having a meeting with Andreas on Friday to update him on the status, do you think it's viable to have one of those PRs done by then?

**Comment by sameerav** [comment]
@noahsark769 Yeah I think that's easier! We don't have the stats backend stuff done for the your impact section right, so I'll do the preference vote section tonight and tomorrow then

**Comment by noahsark769** [comment]
Sounds great!
