### ISSUE TITLE
Mark repayment as incomplete

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#33]
If an org fails to meet a payment, an admin should be able to mark it as failed so that our accounting/reinvestment functions don't think that money exists. I was thinking this could just be a button on the admin dash where they can say this project has failed to repay for this month. As a result, the number we show for how much has been repaid would not include the amount expected for that month.

**Comment by noahsark769** [comment]
@vivekraghuram shouldn't we just be able to aggregate over all repayments to figure out how much has been repayed, rather than trying to do a calculation based on the number of months which may not be correct if an org fails a repayment?

**Comment by noahsark769** [comment]
With the new refactor being tackled by @aykamko this week, this will not be an issue because we'll never assume we have repayments on a monthly basis. Ergo, closing :)
