### ISSUE TITLE
Put "My Impact" under "Manage" in the donor dashboard

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#344]
@sameerav right now, "My Impact" looks like a heading with no content rather than a link itself. I think it should go under "Manage" next to the change password and logout links. What do you think?

**Comment by sameerav** [comment]
@noahsark769 I think that would look better but I'm not sure if it makes sense - "my impact" is not a managing task right?

**Comment by noahsark769** [comment]
Yeah that's true. Maybe we could at least reduce the margin on "My Impact"
and put it at the top, before the projects

**Comment by sameerav** [comment]
Sure, I'll make it fit in better/look better
