### ISSUE TITLE
Unify design of tables in the Dashboard

### ISSUE THREAD

**Issue by erictshen** [calblueprint/revolv#390]
As of now, the tables in the dashboard are different. This will be a quick fix to unify the design of the two tables.

![screen shot 2015-07-26 at 9 56 11 pm](https://cloud.githubusercontent.com/assets/2114482/8898880/671646ea-33e1-11e5-80b2-7eb3d1495d5c.png)
![screen shot 2015-07-26 at 9 56 18 pm](https://cloud.githubusercontent.com/assets/2114482/8898881/69d6d368-33e1-11e5-88a8-77d8fce4a946.png)

**Comment by erictshen** [comment]
This is a quick fix, I'll submit a pull request sometime this week to fix things up!

**Comment by noahsark769** [comment]
Great!
