### ISSUE TITLE
Integrate solar log info into dashboard

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#40]
This should be doable by just downloading csv's from their site. Use the data to create graphs on solar panel output for projects that have completed funding and had their solar panels installed. This should be on the donor dashboard and on the project page (use the same code). 

Vivek: I've been working on figuring out the url to request for the csv and I've trimmed down the urls to this 
1. http://home.solarlog-web.net/sds/modul/SolarLogWeb/Statistik.php?logid=0&c=1775&mode=1&offset=0&flag=32&ex=csv
2. http://home.solarlog-web.net/sds/modul/SolarLogWeb/Statistik.php?logid=0&c=2275&mode=1&offset=0&flag=32&ex=csv

The first is for the dance center and the second for the synagogue by changing the offset to negative numbers you move it backwards a month so -1 would be october, -2 is september, etc. The "c" parameter seems to refer to the actual solar installation but I can't figure out where that number is coming from. If you can find an easy what to get 'c' then you should be able to get the csv's really easily. Perhaps you can make a field on a completed project where they enter a url which would have that 'c' parameter in it?

**Comment by noahsark769** [comment]
I'm actually gunna wait on doing this until the dashboard styles are done
