### ISSUE TITLE
Mailer events

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#51]
RE-volv needs to send emails occasionally. For their newsletters and campaign announcements and things, they just use the mailchimp api, but we need to implement emailing a specific user or all users in two cases:

- [x] Post donation, we should send the donor who donated a nice email thanking them and giving them a summary of their donation, and their tax deductible receipt. (#123)
- [x] We need to set up a monthly job that sends an "engagement email" to all donors giving them a summary of their reinvestment amounts. I think if there's not enough for reinvestment yet, this can be just an update on how each project is going, but all the projects they've donated to should be in this email. (#125)

**Comment by noahsark769** [comment]
This is actually done! HTML emails are not there technically, but they are low priority at this point.
