### ISSUE TITLE
Project page styles

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#64]
Implement the front end of the project page so it is styled super pretty. Follow our jaylin's mockups.

**Comment by noahsark769** [comment]
https://projects.invisionapp.com/share/SR1FVZ8P5#/screens/44276195?maintainScrollPosition=false

**Comment by sameerav** [comment]
![projectlist](https://cloud.githubusercontent.com/assets/7706852/6163163/4ecf3fb2-b243-11e4-9bbe-dbbe9dc9289a.png)
![projectpage](https://cloud.githubusercontent.com/assets/7706852/6163164/4ed1a0ea-b243-11e4-9a7f-3437893fedb2.png)

@noahsark769 @andylouisqin @erictshen @aykamko what do you guys think of these? The box on the right on the project page is what would show for an administrator

I'll start making them tonight if you guys approve! :)

**Comment by andylouisqin** [comment]
the “elevate affrica” view has a good layout! i’m iffy on the left sidebar, it leaves some whitespace in the upper left corner and would prefer if the text was accompanied with associated images so it doesn’t have the craigslist feel.

hoping to give the “donate now” button more emphasis. we can discuss ways of doing this in meeting, but it starts with size and inverting the color scheme, so it’s green with a white font.

I’m really digging the layout of the overall projects page. generally my cardinal rule with fonts is to make sure not to put black fonts over images, but try to put a gradient overlay or something that will let you get away with a white font on top. this way if the user uploads a dark image, they won’t have to worry about the words being unreadable.

also a question: will the images above donate always be those 3 people, or is it expected to be interchanged or customized in some way?

**Comment by sameerav** [comment]
Thanks Andy!
Good point, the sidebar does look craiglistl-y - I'll try to find a better way to handle the menu. What did you mean by associated images though?

Will do on the gradient overlay and I'll try out the emphasis on the "donate now" button!

The people there are a simple filler graphic for now but I was thinking maybe putting the graphic associated with each category there could be nice.

**Comment by noahsark769** [comment]
1. So are these the styles that would show on the regular project page e.g. /project/1/ or the dashboard e.g. /dashboard/#proj1 ? Seems like the dashboard to me, which is fine, but I just want to make sure
2. I agree with andy about the vertical positioning of the left sidebar, the heading on that should match the vertical placement of the project title, but I really like the sidebar aesthetically!
3. I agree about inverting the donate button, that would be cool. Maybe make it revolv blue, similar to how the login button is on hover?
4. I also agree about the gradient. One thing we might want to try: this is the view of the donor seeing a project they've already donated to, so why not have some kind of stat about your impact on the project?
5. For the illustrations, I think we're going in the right direction! However in the final version I think the colors should be consistent with the front page infographic
6. We can definitely overlay the title on the image for the second mockup, that would be fun
7. Where you have the lorem ipsum now would be a great place for project updates also?
8. I like the general idea of the boxes on the side, they seem pretty plain now though. Also we should def align them with the photo, that will create even more of a perceptible kind of association between the photo and the stats.
9. For impact we should for sure use the same svg icons from the home screen! (the cloud, the little people, etc)

**Comment by sameerav** [comment]
1. I was thinking the first one is the dashboard and the second one is the project page. I added a menu on the project page to make it easier to switch from project to project.
2. Okay, will move it up!
3. Will try!
4. I agree! I'll try to add something.
5. For sure! These are just filler graphics.
6. The blue box was supposed to be a video (sorry for not making that clear :( )
7. Sounds good!
8. For sure - I was also thinking that maybe really simple boxes with nice but simple animations could be cool.
9. Okay! :)

**Comment by noahsark769** [comment]
Closing this in favor of #178
