### ISSUE TITLE
Sign up for newsletter during registration

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#72]
Look at the mailchimp api and sign them up for the newsletter using that. This should be a checkbox during the sign up process. Make it checked by default and if it is checked then sign them up.

**Comment by noahsark769** [comment]
This is a good idea! We'll have to look into how the mailchimp api works: not sure if it's just you copy and paste a million email addresses in there, or if you have some kind of database going, or what.

RE-volv will use mailchip separately from this app for sending out the newsletter updates, but if we had some way to tell them who wanted to be subscribed and who didn't, that would be really nice.
