### ISSUE TITLE
Backend for associating users with preferred categories

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#80]
Users need to be able to vote for where they think re-volv should invest next. Or perhaps they can state preferences of where re-volv should invest next. Administrators should be able to indicate what the options are or they can be some set categories? Administrators should be able to see the results on their dashboard. 

THINGS THAT NEED TO BE DONE TO CLOSE THIS ISSUE:

1. Associate RevolvUserProfile with Category
2. Modify @aykamko's algorithm for reinvestment to take money from the pools of people who want it first.
3. Write a bunch of tests for this

UI will be implemented later on the dashboard page.

**Comment by noahsark769** [comment]
@erictshen you got this!
